version: "3.9"

services:
  alclinic-backend:
    image: alclinic-backend:latest
    container_name: alclinic-backend
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "4040:4040"
    environment:
      PORT: ${PORT}
      MONGODB_CLOUD_URL: ${MONGODB_CLOUD_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - alclinic-net

networks:
  alclinic-net:
    driver: bridge
